### PR TITLE
feat: use dbus for notifications

### LINKED ISSUE #36: Notifications through org.freedesktop.Notifications
Thank you for making this program. I like it, and I can't find any other programs which nicely fill the role it fills on my desktop.

Instead of using the QT System Tray icon showMessage notifications, should/could it use freedesktop notifications?

I have made a [fork of this project](https://github.com/Tass0sm/powerkit) and added the code to do this there. It's mainly taken from the notification code used in [flameshot](https://github.com/flameshot-org/flameshot/blob/master/src/utils/systemnotification.cpp). I'm not sure if what I've made is too good, but it seems to work. If this is something worth adding to the real project, I could open a pull request.

Please let me know if that is a good idea.

### PR DESCRIPTION
**Pull request by snprajwal**
Fixes #36 

I mostly fixed and made @Tass0sm's solution work, do let me know if it's possible for me to credit them for the contents of the commit.

### CODE REVIEW

**Comment by rodlie** [comment]
> do let me know if it's possible for me to credit them

You can add the person as co-author in the commit.

Regarding the PR:

The notify class should have the systray as a fallback, not remove it IMHO.

- If dbus notify is available use that else fallback to systray.

---

I will need to setup a dedicated laptop for powerkit development/testing, can do so this weekend.

**Comment by snprajwal** [comment]
@rodlie did you get any time to take a closer look at this?

**Comment by snprajwal** [comment]
ping @rodlie

**Comment by rodlie** [comment]
I don't have time to test anything until next week. Too much stuff do to before Christmas :)

**Comment by snprajwal** [comment]
Of course, no worries. Merry Christmas :D

**Comment by snprajwal** [comment]
@rodlie I've fixed CI for now, we should probably upgrade the project to use Qt6 soon, since Qt4 is fully deprecated, and Qt5 is on the way to deprecation

**Comment by rodlie** [comment]
Hi,

Sorry for the late reply, finally had some time to work on powerkit. There were several issues that had to be resolved, mostly changes in org.freedesktop.PowerManagement etc since I used it last. I have a lot of pending commits, so I will delay testing notifications for a week or so. Don't worry, I will include your changes.

**Comment by rodlie** [comment]
Regarding Qt.

I have already removed support for Qt4. Qt 5.6 is now the minimum required version. I will also fix remaning deprecated warnings for Qt 5.15.

Feel free to test and fix Qt6 issues, but don't break Qt5.

**Pull request merged**
